format = """
$directory\
$git_branch\
$git_status\
$aws\
${custom.kubernetes}\
$fill\
$cmd_duration\
$time\
\n$character
"""

add_newline = true

[fill]
symbol = '─'

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = ' ' # nf-fa-folder_open
home_symbol = '~'
read_only = ' 󰌾 ' # nf-md-lock
style = 'bold fg:#313244 bg:#80EBDF'
read_only_style = 'bold fg:#313244 bg:#80EBDF'
format = """
[](fg:#80EBDF)\
[$path]($style)\
[$read_only]($read_only_style)\
[](fg:#80EBDF)\
"""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# AWS module
[aws]
format = '[$symbol $profile ]($style)'
symbol = "☁️"
style = "bold fg:#ffcb6b"

[gcloud]
disabled = true

# Enable per repository with: touch "$(git rev-parse --git-path show-kubernetes-context)"
[custom.kubernetes]
command = "kubectl config current-context 2>/dev/null"
when = 'test -f "$(git rev-parse --git-path show-kubernetes-context 2>/dev/null)"'
symbol = "󱃾 "
style = "bold cyan"
format = '[$symbol$output]($style) '

[git_branch]
symbol = ""
style = "fg:#769ff0 bg:#1d2230"
format = """
[](fg:#1d2230)\
[$symbol $branch]($style)\
"""

[git_status]
style = "fg:#769ff0 bg:#1d2230"
format = """
[$all_status$ahead_behind]($style)\
[](fg:#1d2230)\
"""

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[$duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
format = '[[   $time ](fg:#a0a9cb)]($style)'

[character]
vimcmd_symbol = '[V](bold green) '
